### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by Breefield** [adafruit/Adafruit_CircuitPython_LIS3MDL#13]
I'm just running the exact example code from https://github.com/adafruit/Adafruit_CircuitPython_LIS3MDL/blob/master/examples/lis3mdl_lsm6ds_test.py
```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 15, in <module>
TypeError: 'module' object is not callable
```

From my Adafruit Feather STM32F405 Express with libs: `adafruit_lis3mdl.mpy`, and `adafruit_lsm6ds`

**Comment by FoamyGuy** [comment]
I think this is due to the lsm6ds library getting split apart from a single file into a module. The import needs to be done slightly differently now. This exapmle shows the new way to do the import: https://github.com/adafruit/Adafruit_CircuitPython_LSM6DS/blob/master/examples/lsm6ds_lsm6dsox_simpletest.py

The main thing that needs to change is including the specific type of module you have in the import statment like this:
```python
from adafruit_lsm6ds.lsm6dsox import LSM6DSOX
```
I can work on updating the example in this repo over the upcoming weekend to resolve this if no one gets to it before then.

**Comment by Breefield** [comment]
Ah yes, that was it.

**Comment by siddacious** [comment]
ah, lame! My mistake. I'll fix and test all the examples.

**Comment by siddacious** [comment]
> ah, lame! My mistake. I'll fix and test all the examples.

looks like @Breefield beat me to it! 👀 @ #14 now

**Comment by siddacious** [comment]
Fixed, thanks @Breefield :)
